### ISSUE TITLE
Coger parser y recorrer el fichero de texto

### ISSUE THREAD

**Issue by PabloTorrecillas** [PabloTorrecillas/IndiWebClient#5]
Coger el fichero XML que ha llegado e ir recorriendolo y obteniendo las diferentes etiquetes y ver cada una de ella y su futuro análisis que haremos sobre cada una de ella.

**Comment by PabloTorrecillas** [comment]
Lo he hecho con Text, Number y Switch, pero no se que ficheros contienen los Blobs y Light, por tanto no he podido parsear esos ficheros.

**Comment by zerjillo** [comment]
Perdona Pablo.

El finde ha estado el niño malo y ahora estoy yo con gastroenteritis.

Mañana imposible quedar, tengo q recuperarme q no me tengo.

El driver de simulador de ccd tiene blobs cuando conectes (por ejemplo con kstars). Lights ahora no recuerdo.

Zerjillo

**Comment by PabloTorrecillas** [comment]
Hola Sergio,
No te preocupes por nada, lo primero es recuperarse.

Ya he encontrado con el ccd el blob.

Esta semana puedo quedar todos los dias menos el miercoles por la mañana,
asi que cuando te venga bien y estes recuperado podemos vernos.

Un saludo y que te mejores!,
Pablo

Enviado desde Samsung Mobile

**Comment by PabloTorrecillas** [comment]
Todo eso está ya hecho en los ficheros anteriores. Ahora ya está bien parseado y subido en el fichero parser.html
