### ISSUE TITLE
Mostrar o no los input type = text

### ISSUE THREAD

**Issue by PabloTorrecillas** [PabloTorrecillas/IndiWebClient#9]
En caso de ser el perm = ro; al ser read only, solamente mostrar el label y su valor. Para otro tipo de caso, en el cual pueda ser modificado, mostrar el input type = text.

**Comment by PabloTorrecillas** [comment]
No se exactamente como hacer el if dentro del div.
He estado investigando bastante fuentes y ninguna dice exactamente como hacerlo.

**Comment by PabloTorrecillas** [comment]
He pensado una cosa: Crear una función aparte, que unicamente haga la comprobación del perm y si es distinto de ro que ponga la caja, si es igual a ro que no la ponga. Todo en el if de la función que me cree y después llamarla dentro de los div

**Comment by PabloTorrecillas** [comment]
La función me funciona pero hay un problema. Me muestra cuando el input cuando el perm != ro, pero, cuando perm == ro, me muestra el mensaje de undefined.

Intentar solucionar el error!

**Comment by zerjillo** [comment]
Si la función javascript no devuelve nada, se devuelve "undefined". 
Prueba en el else a devolver la cadena vacia ""

El 10/10/15 a las 21:04, Pablo Torrecillas escribió:

> La función me funciona pero hay un problema. Me muestra cuando el input
> cuando el perm != ro, pero, cuando perm == ro, me muestra el mensaje de
> undefined.
> 
> Intentar solucionar el error!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PabloTorrecillas/IndiWebClient/issues/9#issuecomment-147117431.

## 

S. Alonso, Ph.D.
Software Engineering Department
University of Granada, Granada, Spain

**Comment by PabloTorrecillas** [comment]
Al devolver la cadena vacía ya si me ha funcionado. Cerrando!
